FROM nginx:alpine
COPY ./ClientApp/ /var/www/
COPY nginx.conf /etc/nginx/nginx.conf
ENV SignaWelDb=Data Source=10.128.13.115,1433;Initial Catalog=pvl_db;Integrated Security=False;User ID=pvl_user_1;Password=PVL2019!;Pooling=False
EXPOSE 80
